baseURL = "/"
languageCode = "de-de"
title = "Kytaara"

ignoreErrors = ["error-remote-getjson"]

paginate = "3"
copyright = 'A template by [Heksagon](https://www.heksagon.net "Your most friendly developer"); edited by Sabrina Frank'
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[minify]
disableCSS = false
disableHTML = false
disableJS = false
disableJSON = false
disableSVG = false
disableXML = false
minifyOutput = true

[minify.tdewolff.html]
keepWhitespace = false

[params]
env = "production"
author = ""
description = "Stoner & Doom Metal made in Nuernberg"
math = false
images = [ "/uploads/og.png" ]
comments = false
mainSections = [ "live" ]
ShowShareButtons = false
ShowCodeCopyButtons = false
ShowRelated = false
CookieNotice = "Wir verwenden Cookies, um deine Erfahrung auf unserer Website zu verbessern und relevante Werbung zu zeigen."
CookieLink = "/legal/datenschutz/#Cookies"
CookieButton = "Cookies Policy"
disableAnchoredHeadings = false
ShowReadingTime = false
ShowBreadCrumbs = true

#[params.analytics.google]

#[params.analytics.yandex]

#[params.analytics.bing]

  [params.label]
  title = "&nbsp&nbspKytaara"
  text = "NBG Doom"
  lightNavIcon = "/uploads/logo.svg"
  darkNavIcon = "/uploads/logo.svg"
  iconHeight = "35"
  iconWIdth = "35"

  [params.assets]
  disableFingerprinting = false
  favicon = "/favicon_io/favicon.ico"
  favicon16x16 = "/favicon_io/favicon-16x16.png"
  favicon32x32 = "/favicon_io/favicon-32x32.png"
  apple_touch_icon = "/favicon_io/apple-touch-icon.png"
  safari_pinned_tab = "/favicon_io/android-chrome-192x192"

  [params.homepage]
  disableHeroSection = false
  heroTitle = "Kytaara"
  heroDescription = "Stoner & Doom Metal made in Nuernberg"
  heroCTAPrimaryText = "Erlebe uns live"
  heroCTAPrimaryUrl = "/live/"
  heroCTASecondaryText = "Wer wir sind"
  heroCTASecondaryUrl = "/about/"
  heroBackgroundImage = "/uploads/bg-head.png"

  disableAboutSection = false
  aboutTitle = "Bio"
  aboutDescription = "Metal made in Nürnberg."
  aboutImgUrl = "/uploads/band-private.png"
  aboutContent = "Wir sind eine junge Band aus Nürnberg, bestehend aus fünf Musiker*innen, die Einflüsse aus den Genres Stoner, Doom, Sludge, Core bis hin zum Blackmetal vereinen. Das Resultat ist eine stets breite Soundwand aus treibenden Riffs und spährischen Klangteppichen. Markenzeichen sind die vielen vornehmlich Orange und Sunn O))) Amps sowie drei fein aufeinander abgestimmte Gitarren, die diesen vollen Klangkörper möglich machen. Unentbehrliches Zentrum der Band sind die Bandbohnen, ohne die keine Probe stattfinden kann."
  disableBlogSection = false
  blogTitle = "Live"
  blogDescription = "Live-Auftritte von Kytaara."
  seeMoreText = "Alle Auftritte" #ToDo: Aktivieren, wenn mehr als 6

  disablePortfolioSection = false
  portfolioTitle = "Musik"
  portfolioDescription = "Hier werden bald unsere Songs zu finden sein. Stay tuned."

    #[[params.homepage.portfolio]]
    #imageUrl = "/uploads/portfolio-1.webp"
    #description = "Erste Single"

    #[[params.homepage.portfolio]]
    #imageUrl = "/uploads/portfolio-2.webp"
    #description = "Portfolio Two."

    #[[params.homepage.portfolio]]
    #imageUrl = "/uploads/portfolio-3.webp"
    #description = "Portfolio Three."

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = "0"
  distance = "1000"
  threshold = "0.4"
  minMatchCharLength = "0"
  keys = [ "title", "permalink", "summary", "content" ]

[[params.plugins.css]]
link = "plugins/css/pico.min.css"

[[params.plugins.js]]
link = "plugins/js/feather.min.js"

#[[menus.main]]
#name = "Blog"
#title = "Blog"
#pre = "pen-tool"
#url = "/blog"
#weight = "20"

[[menus.main]]
name = "Live"
title = "Live"
url = "/live"
weight = "10"

[[menus.main]]
name = "about"
title = "Über uns"
url = "/about"
weight = "20"

#[[menus.main]]
#name = "musik"
#title = "Musik"
#url = "/music"
#weight = "30"

[[menus.main]]
name = "contact"
title = "Kontakt"
url = "/kontakt"
weight = "30"

[[menus.main]]
name = "downloads"
title = "Downloads"
url = "/downloads"
weight = "40"

#[[menus.main]]
#name = "Search"
#title = "Search"
#pre = "search"
#url = "/search"
#weight = "50"

#[[menus.search]]
#name = "Musik"
#title = "Musik"
#url = "/musik"
#weight = "10"

#[[menus.search]]
#name = "Auftritte"
#title = "Auftritte"
#url = "/live"
#weight = "20"
